# Generated by Django 3.1.2 on 2020-10-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='data_type',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
