# Generated by Django 3.1.2 on 2020-10-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
