# Generated by Django 3.1.2 on 2020-10-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201017_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.CharField(default='2020/10/01 12:05:00', max_length=50),
        ),
    ]
