# Generated by Django 3.1.2 on 2020-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201003_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='subject',
            field=models.CharField(default='candidate', max_length=100),
        ),
    ]
