# Generated by Django 3.1.2 on 2020-10-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20201017_1535'),
        ('leads', '0003_auto_20201017_1638'),
    ]

    operations = [
    ]
