# Generated by Django 3.1.2 on 2020-11-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_merge_20201023_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='pn',
            new_name='P_N',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='lead',
            name='ASS',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='lead',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.CharField(default='2020/10/01', max_length=50),
        ),
    ]
