# Generated by Django 3.1.2 on 2020-11-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20201114_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='url',
        ),
    ]
