# Generated by Django 3.1.2 on 2020-11-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='index',
            new_name='name',
        ),
    ]
