# Generated by Django 3.1.2 on 2020-11-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20201111_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=88),
        ),
    ]
