# Generated by Django 3.1.2 on 2020-11-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='2020/10/01', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('index', models.CharField(default='stonk', max_length=5)),
            ],
        ),
    ]
