# Generated by Django 3.1.2 on 2020-11-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='pn',
            new_name='P_N',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='stocks',
            name='ASS',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='stocks',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.CharField(default='2020/10/01', max_length=50),
        ),
    ]
